name: boost_pt_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  #when back button is pressed to exit the app
  fluttertoast: ^8.0.8
  #google icon
  font_awesome_flutter: ^9.2.0
  #for displaying the logo video
  video_player: ^2.2.18

  websafe_svg: ^2.1.1
  animated_text_kit: ^4.2.1
  lottie: ^1.2.2
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7

  firebase_messaging: ^11.2.13
  flutter_local_notifications: ^9.4.0
  #for connection check
  connectivity_plus: ^2.2.0


  #for selecting images from phone
  image_picker: ^0.8.4+9
  file_picker: ^4.5.1
  #for saving variable states even the application is closed
  shared_preferences: ^2.0.13
  #the drawer used along the application
  flutter_zoom_drawer: ^2.3.1
  #animated transitions between the page
  page_transition: ^2.0.5


  #for biometric_auth:
  local_auth: ^2.1.0
  #for enabling flutter switcher_button:
  flutter_switch: ^0.3.2
  #for showing images by url from firebase
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.1
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.0

  #used to link firebase with flutter application
  flutterfire_cli: ^0.1.1+2

  google_fonts: ^3.0.1

  #bottom nav. bar
  curved_navigation_bar: ^1.0.3
  #for flutter pop up alerts
  rflutter_alert: ^2.0.4
  email_auth: ^1.0.0
  intl_phone_field: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.9.2

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/LgoFinal.png"
#  remove_alpha_ios: true
#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_forground: "assets/LgoForground.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/video1.mp4
    - assets/Picture2.png
    - assets/LgoFinal.png
#    - assets/chatBackground.png
    - assets/LgoForground.png
    - animations/pending.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
