// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfIObygOBVkUXNAeXRhGs6l7FghE8_4Y',
    appId: '1:82676782518:android:16bdbb6ecc9b979d0ddd17',
    messagingSenderId: '82676782518',
    projectId: 'boost-pt',
    databaseURL: 'https://boost-pt-default-rtdb.firebaseio.com',
    storageBucket: 'boost-pt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcjwvVMN3-B4DqejeLyamBaHwrhB6tEU',
    appId: '1:82676782518:ios:f0724c851b033c5b0ddd17',
    messagingSenderId: '82676782518',
    projectId: 'boost-pt',
    databaseURL: 'https://boost-pt-default-rtdb.firebaseio.com',
    storageBucket: 'boost-pt.appspot.com',
    androidClientId: '82676782518-4us9ksohv93td14qrshu1u82ak1osd65.apps.googleusercontent.com',
    iosClientId: '82676782518-q51h21ln128tbr5qdjokbm3f9482g6uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.boostPtNew',
  );
}
